version: '3'

services:
    app:
      build: .
      image: mc-laravel-rest
      container_name: mc-laravel-rest
      tty: true
      entrypoint: ./.docker/app/entrypoint.sh
      environment:
        - APP_HOST=app
        - PORT_HOST=9000
      volumes:
        - .:/var/www
      networks:
        - app-network

    nginx:
      build: .docker/nginx
      image: mc-laravel-nginx
      container_name: mc-laravel-nginx
      restart: always
      tty: true
      depends_on:
          - app
      ports:
        - "8001:80"
      volumes:
        - .:/var/www
      networks:
        - app-network

networks:
  app-network:
      driver: bridge
